// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func PositionForm(swapTarget string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"/crop\" id=\"posForm\" hx-target=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(swapTarget)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/positionForm.templ`, Line: 7, Col: 24}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-swap=\"innerHTML\" hidden><input type=\"number\" class=\"pos-input\" name=\"a\" required> <input type=\"number\" class=\"pos-input\" name=\"b\" required> <input type=\"number\" class=\"pos-input\" name=\"x\" required> <input type=\"number\" class=\"pos-input\" name=\"y\" required> <input type=\"number\" class=\"pos-input\" name=\"width\" required> <input type=\"number\" class=\"pos-input\" name=\"heigth\" required><script>\n        let submitPosFormTimer;\n        const clearPosFormDebounce = function() {\n            clearTimeout(submitPosFormTimer)\n        }\n        const submitPosFormDebounce = function () {\n            submitPosFormTimer = setTimeout(() => {\n                const form = document.getElementById(\"posForm\")\n                htmx.trigger(form, 'submit')\n            }, 300); // 300ms delay\n        }\n        const PosFormIsValid = function () {\n            const inputs = any(\".pos-input\")\n            const allFilled = inputs.every((inp) => inp.value !== \"\");\n            console.log(inputs[2].value - inputs[0].value)\n            return allFilled && inputs[2].value - inputs[0].value >= 1 && inputs[3].value - inputs[1].value >= 1\n        }\n        const clearPosForm = function () {\n            const inputs = any(\".pos-input\")\n            inputs.forEach(i => i.value = \"\")\n        }\n        const fillPosForm = function (a, b, x, y, width, heigth) {\n            const inputs = any(\".pos-input\")\n            if (a > x) {\n                [a, x] = [x, a]\n            }\n            if (b > y) {\n                [b, y] = [y, b]\n            }\n            inputs[0].value = a\n            inputs[1].value = b\n            inputs[2].value = x\n            inputs[3].value = y\n            inputs[4].value = width\n            inputs[5].value = heigth\n        }\n    </script></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
