name: Build and Publish Go Project

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Tesseract dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libtesseract-dev

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        go build -o ocr-webui

    - name: Run tests
      run: go test ./... 

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ocr-webui
          LICENSE 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
