name: Build and Publish Go Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Tesseract dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libtesseract-dev

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        go build -o ocr-webui

    - name: Run tests
      run: go test ./...

    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: |
        # Replace with your publishing commands
        echo "Publishing the build..."
        # Example: Upload the artifact
        mkdir -p release
        cp ocr-webui release/
        tar -czvf release/ocr-webui.tar.gz -C release ocr-webui

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: ocr-webui
        path: release/ocr-webui.tar.gz
