name: Build and Publish Go Project

on:
  push:
    branches:
      - main  # Change to your main branch if it's different
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'  # Specify your Go version here

    - name: Build
      run: |
        go build -o ocr-webui ./...  # Adjust the output name and path as necessary

    - name: Run tests
      run: go test ./...  # Run your tests

    - name: Publish
      if: github.ref == 'refs/heads/main'  # Only publish from main branch
      run: |
        # Replace with your publishing commands
        echo "Publishing the build..."
        # Example: Upload the artifact
        mkdir -p release
        cp ocr-webui release/
        tar -czvf release/ocr-webui.tar.gz -C release ocr-webui

    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: ocr-webui
        path: release/ocr-webui.tar.gz
